# Doctrine Configuration
doctrine:
    dbal:
      annotation:
          driver:   ~
          host:     ~
          port:     ~
          dbname:   %database_name_annotation%
          user:     ~
          password: ~
          charset:  ~
    orm:
      annotation:
          connection: annotation
          mappings:
              PageAnnotatorBundle:
                  type: annotation