page-annotator-save:
    path:     /save
    defaults: { _controller: PageAnnotatorBundle:Annotation:save }

page-annotator-delete:
    path:     /delete
    defaults: { _controller: PageAnnotatorBundle:Annotation:delete }

page-annotator-delete_all:
    path:     /deleteAll
    defaults: { _controller: PageAnnotatorBundle:Annotation:deleteAll }