save:
    path:     /annotations/save
    defaults: { _controller: PageAnnotatorBundle:Annotation:save }

delete:
    path:     /annotations/delete
    defaults: { _controller: PageAnnotatorBundle:Annotation:delete }

delete_all:
    path:     /annotations/deleteAll
    defaults: { _controller: PageAnnotatorBundle:Annotation:deleteAll }
