save:
    path:     /save
    defaults: { _controller: PageAnnotatorBundle:Annotation:save }

delete:
    path:     /delete
    defaults: { _controller: PageAnnotatorBundle:Annotation:delete }

delete_all:
    path:     /deleteAll
    defaults: { _controller: PageAnnotatorBundle:Annotation:deleteAll }
