page_annotator_save:
    path:     /save/
    defaults: { _controller: PageAnnotatorBundle:Annotation:save }

page_annotator_search:
    path:     /search/{url}
    defaults: { _controller: PageAnnotatorBundle:Annotation:search }

page_annotator_delete:
    path:     /delete/
    defaults: { _controller: PageAnnotatorBundle:Annotation:delete }

page_annotator_delete_all:
    path:     /deleteAll/
    defaults: { _controller: PageAnnotatorBundle:Annotation:deleteAll }

page_annotator_delete_all_by_url:
    path:     /deleteAllByUrl/
    defaults: { _controller: PageAnnotatorBundle:Annotation:deleteAllByUrl }