page_annotator_save:
    path:     /save/
    defaults: { _controller: PageAnnotatorBundle:Annotation:save }

page_annotator_delete:
    path:     /delete/
    defaults: { _controller: PageAnnotatorBundle:Annotation:delete }

page_annotator_delete_all:
    path:     /deleteAll/
    defaults: { _controller: PageAnnotatorBundle:Annotation:deleteAll }

page_annotator_get_all:
    path:     /getAll/
    defaults: { _controller: PageAnnotatorBundle:Annotation:getAll }